name: summary
on:
  pull_request:
jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
    steps:
      # Checkout only needed for developing
      - name: Checkout
        uses: actions/checkout@v3

      - name: Watch GitHub Checks
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
